version: '3'
services:
  app:
    build: ./app
    restart: always
    ports:
      - "8000:8000"
    environment:
      DB_USER: "postgres"
      DB_PASSWORD: "password"
      DB_URL: "postgres"
      DB_NAME: "resto"
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "resto"
      POSTGRES_PASSWORD: "password"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
