version: '3.8'
services:
  app:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      DB_USER: "postgres"
      DB_PASSWORD: "password"
      DB_URL: "postgres"
      DB_NAME: "resto"
    command: "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    networks:
      - resto_network
    depends_on:
      - postgres

  postgres:
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_DB: "resto"
      POSTGRES_PASSWORD: "password"
    networks:
      - resto_network
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
  resto_network:
    name: resto_network
