version: '3.8'
services:
  app:
    build: .
    restart: always
    ports:
      - "8000:8000"
    env_file: .env.example
    command: "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    networks:
      - resto_network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:15.1-alpine
    restart: always
    env_file: .env.example
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - resto_network
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    env_file: .env.example
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - resto_network


volumes:
  pgdata:

networks:
  resto_network:
    name: resto_network
