version: '3.8'
services:
  test-app:
    build: .
    env_file: .env.example
    command: "pytest -vv"
    networks:
      - test_resto_network

networks:
  test_resto_network:
    external:
      name: resto_network
